name: Generate a build and push to another branch

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm ci
        env:
          CI: false

      - name: Build
        run: npm run build

      - name: Push to build branch
        uses: s0/git-publish-subdir-action@develop
        with:
          REPO: ${{ github.repository }}
          BRANCH: build
          FOLDER: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
